#!/usr/bin/env bash

# -- OFFICIAL DOCS: (https://cloud.google.com/sdk/docs/quickstarts)

# -- main function that will call 1 of 2 functions below depending on the detected OS type --

set -x

main () {

# -- create a new project name && email_prefix
# -- see "man bash |grep -i random" for usage of RANDOM 
project="project-$RANDOM"

# -- check OS && call appropriate "function"
if [ -f /etc/redhat-release ]; then
  package_manager="yum"
  install_rhel
fi

# -- check OS && call install "function"
if [ -f /etc/lsb-release ]; then
  package_manager="apt-get"
  install_ubuntu
fi

# -- call export_vars function for direnv
export_vars

}

# -- official install docs: https://cloud.google.com/sdk/docs/quickstart-redhat-centos

install_rhel () 
{
package_manager="yum"

# Update YUM with Cloud SDK repo information:
sudo tee -a /etc/yum.repos.d/google-cloud-sdk.repo << EOM
[google-cloud-sdk]
name=Google Cloud SDK
baseurl=https://packages.cloud.google.com/yum/repos/cloud-sdk-el7-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
       https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
EOM

# install the Cloud SDK from the repo
sudo "$package_manager" install google-cloud-sdk -y

# install tmux 
sudo "$package_manager" install tmux 
}

# --- official docs: https://cloud.google.com/sdk/docs/quickstart-debian-ubuntu

install_ubuntu () 
{

# Add the Cloud SDK distribution URI as a package source
echo "deb http://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list

# Import the Google Cloud Platform public key
curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -

# Update the package list and install the Cloud SDK
sudo "$package_manager" -y update && sudo "$package_manager" -y install google-cloud-sdk

# install tmux
sudo "$package_manager" install tmux -y
}

export_vars ()
{

# set vars for projects
echo 'PATH_add bin
export CLOUDSDK_BILLING_ACCOUNT="xxxxxxxxxx"
export CLOUDSDK_CONFIG=$PWD/gcloud-config
export CLOUDSDK_CORE_PROJECT='"$project"'
export CLOUDSDK_COMPUTE_REGION=us-west1
export CLOUDSDK_COMPUTE_ZONE=us-west1-a
export CLOUDSDK_IAM_EMAIL="${CLOUDSDK_CORE_PROJECT}@${CLOUDSDK_CORE_PROJECT}.iam.gserviceaccount.com"' > $HOME/.envrc
}


# main function to begin program execution
main

